// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwuJvsjFrlEqEzOwK4J5lpJmtrt1JD5TQ',
    appId: '1:897947861625:android:83eff6e36a6db4508b8aa8',
    messagingSenderId: '897947861625',
    projectId: 'contactsafe-ee52f',
    storageBucket: 'contactsafe-ee52f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYVy7pLQmdP357kw7rNl4hpHyI0kQ2cIA',
    appId: '1:897947861625:ios:b1ae2f521b05053b8b8aa8',
    messagingSenderId: '897947861625',
    projectId: 'contactsafe-ee52f',
    storageBucket: 'contactsafe-ee52f.firebasestorage.app',
    iosBundleId: 'com.example.contactsafe',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjEaFTj7w2k_u4vLwDfcuUH35EiOOPnzM',
    appId: '1:897947861625:web:a6fc59cce58448338b8aa8',
    messagingSenderId: '897947861625',
    projectId: 'contactsafe-ee52f',
    authDomain: 'contactsafe-ee52f.firebaseapp.com',
    storageBucket: 'contactsafe-ee52f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYVy7pLQmdP357kw7rNl4hpHyI0kQ2cIA',
    appId: '1:897947861625:ios:b1ae2f521b05053b8b8aa8',
    messagingSenderId: '897947861625',
    projectId: 'contactsafe-ee52f',
    storageBucket: 'contactsafe-ee52f.firebasestorage.app',
    iosBundleId: 'com.example.contactsafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjEaFTj7w2k_u4vLwDfcuUH35EiOOPnzM',
    appId: '1:897947861625:web:02d437ce6018358f8b8aa8',
    messagingSenderId: '897947861625',
    projectId: 'contactsafe-ee52f',
    authDomain: 'contactsafe-ee52f.firebaseapp.com',
    storageBucket: 'contactsafe-ee52f.firebasestorage.app',
  );

}